version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3335:3000"
    env_file: .env
    environment:
      PROCESSING_URL: http://processing:5000
      UPLOAD_DIR: /app/uploads
      RENDER_DIR: /app/rendered
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - uploads:/app/uploads
      - rendered:/app/rendered

  processing:
    build: ./processing
    volumes:
      - ./processing:/app
      - uploads:/app/uploads
      - rendered:/app/rendered

volumes:
  uploads:
  rendered:
